# Generated by Django 5.1.4 on 2025-03-05 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_alter_song_path_to_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorite_by',
        ),
        migrations.AddField(
            model_name='song',
            name='favorite_by',
            field=models.ManyToManyField(related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
